No KVM FOR DOCKER

version: "3"
services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "ltsc10"
      DISK_SIZE: "100G"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      DISK_TYPE: "ide"
      CONSOLE: "Y"
      # HV: "N"
      KVM: "N"
    # devices:
    #   - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    restart: on-failure
